#!/bin/bash
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# bash additions
cd ~/;
source bin/activate;
cd quorum-site;

# set path
export EDITOR="vim"

path="/home/$USER/bin:/home/$USER/yes/bin:/home/$USER/bin:/home/$USER/yes/bin:/home/$USER/bin:"
path+="/usr/local/lib:"
path+="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export PATH="$path"

# better compiler function
#restart_compilers () {
    #echo "Restarting compilers..."
    ## kill all processes
    #ps -ef | awk -v USER=$USER \
        #'$1 == USER && $9 ~ /(stylus|cjsx|coffee)/ {print $2}' | \
        #xargs kill -9

    ## save current working directory
    #cwd=$(pwd)
    #cd ~/quorum-site/app/static/

    ## stylus
    #nohup stylus -w -m --out css/ stylus/ >/dev/null 2>&1 &
    ## cjsx
    #nohup cjsx -mo jsx/ -wcb cjsx/ >/dev/null 2>&1 &
    ## coffee
    #nohup coffee -mo cc/ -wc coffee/  >/dev/null 2>&1 &

    ## return to working directory
    #cd $cwd
#}

compile_static_files () {
    # save current working directory
    cwd=$(pwd)
    cd ~/quorum-site/app/static/

    # stylus
    echo "Compiling Stylus"
    stylus -m --out css/ stylus/
    # cjsx
    echo "Compiling CJSX"
    cjsx -mo jsx/ -c cjsx/
    # coffee
    echo "Compiling Coffee"
    coffee -mo cc/ -c coffee/

    echo "All done - returning to CWD"
    # return to working directory
    cd $cwd
}


###########
# Styling #
###########

# configure colors
reset_color=`tput sgr0`;
green_color=`tput setaf 2`;
red_color=`tput setaf 1`;
purple_color=`tput setaf 5`;

# commands to print messages of different colors
green(){
    echo "${green_color}$1${reset_color}";
}
purple(){
    echo "${purple_color}$1${reset_color}";
}
red(){
    echo "${red_color}$1${reset_color}";
}

####################
# Useful Functions #
####################

# aliases for shell_plus
sp(){
 python manage.py shell_plus
}
shell(){
     python manage.py shell_plus;
}
# runserver
serve(){
    green "### Running Server on port $1...";
    sudo chown -R $USER *
    sudo pkill -f $1
    python manage.py runsslserver 0.0.0.0:$1;
}
# parser
parse(){
    python manage.py parse $1
}

# for deleteing defunct / zombies
kill_zombies() {
    green "### You are now killing python zombies";
    for pid in $(ps -ef | awk '/defunct/ { print $3 }'); do
        kill "$pid";
    done;
    red "### Success: Zombies vanquished";
}

# wipe out swap files
ls_swp() {
    find . -name *swp
}

rm_swp() {
    find . -name *swp -delete;
}

# deployment
reset_remote () {
    # if no input arguments, use the current branch in git
    if [ $# -eq 0 ]
      then
        branchname=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
      else
        branchname=$1
    fi
    echo "Resetting remote to $branchname."
    sudo git clean -fdx
    sudo git reset --hard;
    sudo git fetch origin;
    sudo git checkout $branchname;
    sudo git reset --hard origin/$branchname;
    sudo chown -R $USER *;
    find . -name '*.pyc' -delete
}

#################
# Fun Functions #
#################

quorum_text () {
    echo "";
    purple " \$\$\$\$\$\$\\";
    purple "\$\$  __\$\$\\";
    purple "\$\$ /  \$\$ |\$\$\\   \$\$\\  \$\$\$\$\$\$\\   \$\$\$\$\$\$\\  \$\$\\   \$\$\\ \$\$\$\$\$\$\\\$\$\$\$\\";
    purple "\$\$ |  \$\$ |\$\$ |  \$\$ |\$\$  __\$\$\\ \$\$  __\$\$\\ \$\$ |  \$\$ |\$\$  _\$\$  _\$\$\\";
    purple "\$\$ |  \$\$ |\$\$ |  \$\$ |\$\$ /  \$\$ |\$\$ |  \\__|\$\$ |  \$\$ |\$\$ / \$\$ / \$\$ |";
    purple "\$\$ \$\$\\\$\$ |\$\$ |  \$\$ |\$\$ |  \$\$ |\$\$ |      \$\$ |  \$\$ |\$\$ | \$\$ | \$\$ |";
    purple "\\\$\$\$\$\$\$ / \\\$\$\$\$\$\$  |\\\$\$\$\$\$\$  |\$\$ |      \\\$\$\$\$\$\$  |\$\$ | \$\$ | \$\$ |";
    purple " \\___\$\$\$\\  \\______/  \\______/ \\__|       \\______/ \\__| \\__| \\__|";
    purple "     \\___|  * Data Driven Analytics | Dev Env for $USER *";
    echo "";
}
quorum_text

###pip install autopep8
auto_pep_file(){
    autopep8 --in-place --max-line-length 100 $1
}
style_clean(){
    yapf app/geography/models.py --style "google" -i
}

remove_dos() {
    echo "checking for ^M characters"
    grep -r -l \
        --include \*\*.py \
        --include \*\*.html \
        --include \*\*.coffee | xargs dos2unix
    echo "^M characters were all removed"
}

if [[ "$TMUX" == "" ]] &&
        [[ "$SSH_CONNECTION" != "" ]]; then

    # Attempt to discover a detached session and attach
    # it, else create a new session
    WHOAMI=$(whoami)
    if tmux has-session -t $WHOAMI 2>/dev/null; then
        tmux -2 attach-session -t $WHOAMI
    else
        tmux -2 \
            new-session -s $WHOAMI \; \
            # seems to cause weird problems
            #new-session -s $WHOAMI "vim" \; \
            #split-window "python manage.py runserver 8888" \; \
            #split-window -h "python manage.py shell_plus" \; \
            #select-pane -U \; \
            #resize-pane -D 10
    fi
fi
